[profile.default]
solc_version = '0.8.23'
src = "contracts"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 1000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
sepolia = "${SEPOLIA_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = "mainnet" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia" }
